name: Build and ping FeaturePeek
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use node 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Build
      run: echo "Nothing to do"
    - name: Ping FeaturePeek
      run: bash <(curl -s https://peek.run/ci)
